add task state machine
Graph1589/task-manager pull request #7
Opened 2021-11-18 21:41 UTC by Graph1589

2021-11-19 11:11 UTC, moklidia requested changes

2021-11-19 11:11 UTC, moklidia commented on app/models/task.rb
> +    event :qa do
Названия событий должны быть глаголами

2021-11-19 11:11 UTC, moklidia commented on app/models/task.rb
> +    event :finish do
Неподходящее название для этого события

2021-11-22 12:47 UTC, moklidia requested changes

2021-11-22 12:47 UTC, moklidia commented on app/models/task.rb
> +    event :review do
:test и :review всё-таки неподходящие названия для этих событий. :test - это "протестировать", а здесь мы только отправляем в тестирование. То же самое с :review.
Можно например назвать эти события "send_to_test", "send_to_review"

2021-11-22 12:55 UTC, Graph1589 commented on app/models/task.rb
> +    event :review do
Спасибо!

2021-11-24 19:10 UTC, greybutton approved these changes

2021-11-26 11:50 UTC, merged